//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMetierSharedMemory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public int idCategorie { get; set; }
        public string CodeCategorie { get; set; }
        public string LibelleCategorie { get; set; }
    }
}
